### ISSUE TITLE
Gradle.build ERROR

### ISSUE THREAD

**Issue by pleiadex** [noev/Android-Ethereum-Hello-World#1]
![image](https://user-images.githubusercontent.com/37097363/57919811-946bbf80-78d4-11e9-8df6-890a724eb76c.png)

Hi Noev.

I'm Sungyoun from South Korea.

I've downloaded your code but there is a issue.

I've tried to resolve the error and changed dependency and everything as Google advised me.

However, Nothing is changed. 

**Do you know how to resolve this isssue?**

Thanks for sharing your code on Github.

**Comment by noev** [comment]
Hello Sungyoun,It's an old project using old dependencies.I will make sure to update the project to the latest dependencies during the weekend.Have a nice dayOn May 17, 2019 11:54, SungYounSeo <notifications@github.com> wrote:
Hi Noev.
I'm Sungyoun from South Korea.
I've downloaded your code but there is a issue.
I've tried to resolve the error and changed dependency and everything as Google advised me.
However, Nothing changed.
Do you know how to resolve this isssue?
Thanks for sharing your code on Github.

**Comment by pleiadex** [comment]
Thank you so much for your reply!!

I hope you have a great day :)

I'll build this code after you update it.

Kind Regards,

Sungyoun

**Comment by noev** [comment]
Hi, I updated gradle to the latest version and it compiles fine. But when I try to install it, it fails for me. Could you try whether it works for you now?

**Comment by noev** [comment]
The app was too messy. I just recreated the project, updated gradle and web3j and copy pasted in the old main activity. It should work now.

**Comment by pleiadex** [comment]
![image](https://user-images.githubusercontent.com/37097363/57967220-18867b80-7997-11e9-98f8-855f063bcf95.png)

Thanks for accepting my issue.

I ran the new one and it can be built now!

But, I have another issue.

As you can see the picture that I attached, Logcat says "MainActivity.kt:30" is wrong.

Could you help me to figure out what's going on if you don't mind?

Kindest Regards,

Sungyoun.

**Comment by noev** [comment]
Have you updated these two fields?

![Screen Shot 2019-05-18 at 11 48 38 AM](https://user-images.githubusercontent.com/4701657/57967769-f4a94280-7962-11e9-9c12-4500639bede6.png)

**Comment by pleiadex** [comment]
I am extremely apologetic for not noticing the your provided instructions earlier.

I will test them out and let you know if I have any further complications.

Thank you so much for reply.

Kindest Regards,

Sungyoun

**Comment by noev** [comment]
No worries. 

Happy tinkering.

**Comment by pleiadex** [comment]
![KakaoTalk_20190520_204506114](https://user-images.githubusercontent.com/37097363/58019348-4824b780-7b40-11e9-9039-f0b0cf488fc4.jpg)
Thank you so much!

Now it works correctly.

I'll read your blog and study how smart contract works with Android.

I really appreciate it.

Kindest Regards,

Sungyoun
