### ISSUE TITLE
Solidity source code

### ISSUE THREAD

**Issue by pleiadex** [noev/Android-Ethereum-Hello-World#2]
Hi Noev.

I'm Sungyoun.

I tried to make my own contract and practice with your "android" code.

Could you share your smart contract written in solidity?

I really appreciate it if you reply :)

Kindest Regards,

Sungyoun.

**Comment by noev** [comment]
It should be this


`pragma solidity >=0.4.22 <0.6.0;

contract Mortal {
    /* Define variable owner of the type address */
    address owner;

    /* This constructor is executed at initialization and sets the owner of the contract */
    constructor() public { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() public { if (msg.sender == owner) selfdestruct(msg.sender); }
}

contract Greeter is Mortal {
    /* Define variable greeting of the type string */
    string greeting;

    /* This runs when the contract is executed */
    constructor(string memory _greeting) public {
        greeting = _greeting;
    }

    /* change greeting */
    function changeGreeting(string _greeting) public {
        greeting = _greeting;
    }

    /* Main function */
    function greet() public view returns (string memory) {
        return greeting;
    }
}`

**Comment by noev** [comment]
You can find it under **Your first citizen: the greeter** 

https://github.com/ethereum/ethereum-org/blob/master/views/content/greeter.md

And add 


    function changeGreeting(string _greeting) public {
        greeting = _greeting;
    }

To the greeter contract.
